<!doctype html>
<html lang="en">
<head>
	<title>Page not Found - <?php echo TITLE ?></title>
	<link rel="shortcut icon" type="image/x-icon" href="<?php echo DOMAIN ?>assets/images/favicon.ico">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="<?php echo DOMAIN ?>assets/css/tailwind.min.css">
</head>
<body class="h-screen overflow-hidden flex items-center justify-center" style="background: #edf2f7;">
    <style>

  * {
  	"Whitney SSm A", "Whitney SSm B", "Helvetica Neue", Helvetica, Arial, Sans-Serif;
  }

    .error-text {
      font-size: 130px;
    }

    @media (min-width: 768px) {
      .error-text {
        font-size: 220px;
      }
    }

</style>

<div class="h-screen w-screen bg-blue-600 flex justify-center content-center flex-wrap">
  <p class="font-sans text-white error-text">404</p>
</div>

<div class="absolute w-screen bottom-0 mb-6 text-white text-center font-sans text-xl">
	<span class="opacity-50">Page not Found, go back to</span>
 	<a class="border-b" href="<?php echo DOMAIN ?>">Homepage</a>
</div>
</body>
</html>
