	
	<!--::header part start::-->
    <header class="main_menu home_menu">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-12">
                    <nav class="navbar navbar-expand-lg navbar-light">
                        <a class="navbar-brand" href="index.html"> <img src="<?=DOMAIN?>assets/img/logo.png" alt="logo"> </a>
                        <div class="collapse navbar-collapse main-menu-item" id="navbarSupportedContent">
                            <ul class="navbar-nav">
                                
                                <li class="nav-item">
                                    <a class="nav-link" href="#"></a>
                                </li>
                            </ul>
                        </div>
                        
                    </nav>
                </div>
            </div>
        </div>
        
    </header>
    <!-- Header part end-->

    <!-- banner part start-->
    <section class="banner_part">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-7">
                    <div class="banner_text">
                        <div class="banner_text_iner">
                            <h1>The fast, affordable way to ride.</h1>
                            <p>Download the CoolBoda app and enjoy rides to any destination you desire, with our unique service.</p>
                            <a href="https://play.google.com/store/apps/details?id=com.myteware.rideboda" target="_blank" class="btn_2 banner_btn_1">Download Now</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-5">
                    <div class="banner_img d-lg-block">
                        <img src="<?=DOMAIN ?>assets/img/hero_img.png" alt="" height="600px">
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- banner part start-->

    <!-- feature_part start-->
    <section class="feature_part padding_top">
        <div class="container">
            <div class="row align-items-center justify-content-between">
                <div class="col-lg-6 ">
                    <div class="row align-items-center">
                        <div class="col-lg-6 col-sm-6">
                            <div class="single_feature">
                                <div class="single_feature_part">
                                    <img src="img/feature_icon_1.png" alt="">
                                    <h4>1. Install App</h4>
                                    <p>Download app from Google Play and Install on your device</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6 col-sm-6">
                            <div class="single_feature">
                                <div class="single_feature_part">
                                    <img src="img/feature_icon_2.png" alt="">
                                    <h4>2. Create Account</h4>
                                    <p>Create account using your phone number and Sign In</p>
                                </div>
                            </div>
                            <div class="single_feature">
                                <div class="single_feature_part single_feature_part_2">
                                    <img src="img/feature_icon_3.png" alt="">
                                    <h4>3. Choose your Destination</h4>
                                    <p>Select pick up location and choose your destination address</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-5">
                    <div class="feature_part_text">
                        <h2>How it Works?</h2>
                        <p>Follow this simple steps, and get started now.</p>
                        <div class="row">
                            <div class="col-sm-6 col-md-4 col-lg-5">
                                <div class="feature_part_text_iner">
                                    <h4>50k</h4>
                                    <p>Total Customers</p>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-4 col-lg-5">
                                <div class="feature_part_text_iner">
                                    <h4>100k</h4>
                                    <p>Rides Completed</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <img src="<?=DOMAIN?>assets/img/animate_icon/Shape-1.png" alt="" class="feature_icon_1">
        <img src="<?=DOMAIN?>assets/img/animate_icon/Shape-14.png" alt="" class="feature_icon_2">
        <img src="<?=DOMAIN?>assets/img/animate_icon/Shape.png" alt="" class="feature_icon_3">
        <img src="<?=DOMAIN?>assets/img/animate_icon/shape-3.png" alt="" class="feature_icon_4">
    </section>
    <!-- upcoming_event part start-->

	<!-- about_us part start-->
	<br />
    <section class="about_us right_time section_padding" style="background-color: #cbd7e1;">
        <div class="container">
            <div class="row align-items-center justify-content-between">
                <div class="col-md-6 col-lg-5">
                    <div class="about_us_text">
                        <h2>Google Maps Location</h2>
                        <p>Check out your current location with google maps. We provide a native map expirience so that you can find familiar places.</p>
                        
                    </div>
                </div>
				<div class="col-md-6 col-lg-6">
                    <div class="learning_img">
                        <img src="<?=DOMAIN?>assets/img/map_view.png" alt="">
                    </div>
                </div>
            </div>
        </div>
        <img src="<?=DOMAIN?>assets/img/animate_icon/Shape-1.png" alt="" class="feature_icon_1">
        <img src="<?=DOMAIN?>assets/img/animate_icon/shape.png" alt="" class="feature_icon_4">
    </section>
    <!-- about_us part end-->
	
	<!-- about_us part start-->
    <section class="about_us right_time section_padding">
        <div class="container">
            <div class="row align-items-center justify-content-between">
                <div class="col-md-6 col-lg-6">
                    <div class="learning_img">
                        <img src="<?=DOMAIN?>assets/img/about_img.png" alt="">
                    </div>
                </div>
                <div class="col-md-6 col-lg-5">
                    <div class="about_us_text">
                        <h2>Easy to Use 
                            Mobile Application</h2>
                        <p>Our client app has a user-friendly design and will be easy to install. You can order rides just in two steps. We have wallet Technologie integrated also to allow you to pay cashless.</p>
                        <a href="https://play.google.com/store/apps/details?id=com.myteware.rideboda" target="_blank" class="btn_1">DOWNLOAD</a>
                    </div>
                </div>
            </div>
        </div>
        <img src="<?=DOMAIN?>assets/img/about_shape.png" alt="" class="about_shape_1">
        <img src="<?=DOMAIN?>assets/img/animate_icon/Shape-1.png" alt="" class="feature_icon_1">
        <img src="<?=DOMAIN?>assets/img/animate_icon/shape.png" alt="" class="feature_icon_4">
    </section>
    <!-- about_us part end-->
	
	
	<br />