<?php
	$driver = $this->view_data['driver'];
	$distance = $this->view_data['distanceKm'];
	$rides = $this->view_data['rides'];
	$numusers = $this->view_data['numusers'];
	$numreject = $this->view_data['numreject'];

?>	
	<main class="h-full overflow-y-auto">
        <div class="container px-6 mx-auto grid">
            <h2 class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200"><?=$driver['firstname'].' '.$driver['lastname']?> | <?=$driver['status']?></h2>
			
			<h4 class="mb-4 text-lg font-semibold text-gray-600 dark:text-gray-300">
				Driver Overall Preformance
            </h4>
			<div class="grid gap-6 mb-8 md:grid-cols-2 xl:grid-cols-4">
				<!-- Card -->
				<div class="flex items-center p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800">
					<div class="p-3 mr-4 text-teal-500 bg-teal-100 rounded-full dark:text-teal-100 dark:bg-teal-500">
					  <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
						<path d="M13 6a3 3 0 11-6 0 3 3 0 016 0zM18 8a2 2 0 11-4 0 2 2 0 014 0zM14 15a4 4 0 00-8 0v3h8v-3zM6 8a2 2 0 11-4 0 2 2 0 014 0zM16 18v-3a5.972 5.972 0 00-.75-2.906A3.005 3.005 0 0119 15v3h-3zM4.75 12.094A5.973 5.973 0 004 15v3H1v-3a3 3 0 013.75-2.906z"></path>
					  </svg>
					</div>
					<div>
					  <p class="mb-2 text-sm font-medium text-gray-600 dark:text-gray-400">
						Customer Serviced
					  </p>
					  <p class="text-lg font-semibold text-gray-700 dark:text-gray-200">
						<?=$numusers?>
					  </p>
					</div>
				</div>
				
				<!-- Card -->
				<div class="flex items-center p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800">
					<div class="p-3 mr-4 text-teal-500 bg-teal-100 rounded-full dark:text-teal-100 dark:bg-teal-500">
					  <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
						  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" />
						  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" />
						</svg>
					</div>
					<div>
					  <p class="mb-2 text-sm font-medium text-gray-600 dark:text-gray-400">
						Distance Traveled
					  </p>
					  <p class="text-lg font-semibold text-gray-700 dark:text-gray-200">
						<?=$distance?>
					  </p>
					</div>
				</div>
				
				<!-- Card -->
				<div class="flex items-center p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800">
					<div class="p-3 mr-4 text-teal-500 bg-teal-100 rounded-full dark:text-teal-100 dark:bg-teal-500">
					  <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
						  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 12l3-3 3 3 4-4M8 21l4-4 4 4M3 4h18M4 4h16v12a1 1 0 01-1 1H5a1 1 0 01-1-1V4z" />
						</svg>
					</div>
					<div>
					  <p class="mb-2 text-sm font-medium text-gray-600 dark:text-gray-400">
						Rides Completed 
					  </p>
					  <p class="text-lg font-semibold text-gray-700 dark:text-gray-200">
						<?=count($rides)?>
					  </p>
					</div>
				</div>
				
				<!-- Card -->
				<div class="flex items-center p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800">
					<div class="p-3 mr-4 text-teal-500 bg-teal-100 rounded-full dark:text-teal-100 dark:bg-teal-500">
					  <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
						  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 12l3-3 3 3 4-4M8 21l4-4 4 4M3 4h18M4 4h16v12a1 1 0 01-1 1H5a1 1 0 01-1-1V4z" />
						</svg>
					</div>
					<div>
					  <p class="mb-2 text-sm font-medium text-gray-600 dark:text-gray-400">
						Rides Rejected
					  </p>
					  <p class="text-lg font-semibold text-gray-700 dark:text-gray-200">
						<?=$numreject?>
					  </p>
					</div>
				</div>
            </div>
			
			<h4 class="mb-4 text-lg font-semibold text-gray-600 dark:text-gray-300">
              Personal Information
            </h4>
			<div class="grid gap-6 mb-8 md:grid-cols-2">
				<div class="min-w-0 p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800">
					<h4 class="font-semibold text-gray-600 dark:text-gray-300">
					  Fullname
					</h4>
					<p class="mb-4 text-gray-600 dark:text-gray-400">
					  <?=$driver['firstname'].' '.$driver['lastname']?>
					</p>
					<h4 class="font-semibold text-gray-600 dark:text-gray-300">
					  Phone Number
					</h4>
					<p class="mb-4 text-gray-600 dark:text-gray-400">
					  <?=$driver['phone_number']?>
					</p>
					<h4 class="font-semibold text-gray-600 dark:text-gray-300">
					  Email
					</h4>
					<p class="mb-4 text-gray-600 dark:text-gray-400">
					  <?=$driver['email']?>
					</p>
				</div>
				<div class="min-w-0 p-4 bg-white rounded-lg shadow-xs dark:bg-gray-800">
					<h4 class="font-semibold text-gray-600 dark:text-gray-300">
					  Gender
					</h4>
					<p class="mb-4 text-gray-600 dark:text-gray-400">
					  <?=$driver['gender']?>
					</p>
					<h4 class="font-semibold text-gray-600 dark:text-gray-300">
					  Device Name
					</h4>
					<p class="mb-4 text-gray-600 dark:text-gray-400">
					  <?=$driver['device_name']?>
					</p>
					<h4 class="font-semibold text-gray-600 dark:text-gray-300">
					  Boda Number
					</h4>
					<p class="mb-4 text-gray-600 dark:text-gray-400">
					  <?=$driver['boda_number']?>
					</p>
				</div>
            </div>
			
			
			<!-- New Table -->
			<div class="w-full overflow-hidden rounded-lg shadow-xs mb-8">
				<div class="w-full overflow-x-auto">
					<div class="max-w-screen-lg mx-auto w-full h-full flex flex-col items-center justify-center">
						<div x-data="dataTable()"
							x-init="
							initData()
							$watch('searchInput', value => {
							  search(value)
							})" class="p-5 w-full flex flex-col dark:text-gray-400 dark:bg-gray-800 dark:border-gray-700">
							<div class="relative text-gray-500 focus-within:text-purple-600 dark:focus-within:text-purple-400">
								<div class="p-4">
									<input x-model="searchInput" type="text" class="block w-full pr-10 mt-1 text-sm text-black dark:text-gray-300 dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:focus:shadow-outline-gray form-input" placeholder="Search by Name or Phone Number">
								</div>
							</div>
							
							<table class="w-full whitespace-no-wrap" id="dataTable">
								<thead>
									<tr class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800">
										<th class="px-4 py-3">Reference</th>
										<th class="px-4 py-3">Customer</th>
										<th class="px-4 py-3">Pick Up</th>
										<th class="px-4 py-3">Drop Off</th>
										<th class="px-4 py-3">Distance</th>
										<th class="px-4 py-3">Fair Change</th>
										<th class="px-4 py-3">Payment Method</th>
										<th class="px-6 py-3">Start Time</th>
										<th class="px-6 py-3">End Time</th>
									</tr>
								</thead>
								<tbody class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800">
									<template x-for="(item, index) in items" :key="index">
										<tr x-show="checkView(index + 1)" class="text-sm text-gray-700 dark:text-white">
											<td class="px-4 py-3">
												<a x-bind:href="`<?=DOMAIN?>dashboard/rides/view?rid=${item.reference}`">
													<p class="font-semibold" x-text="item.reference"></p>
												</a>
											</td>
											<td class="px-4 py-3">
												<p class="font-normal" x-text="item.fullname"></p>
											</td>
											<td class="px-4 py-3">
												<p class="font-normal" x-text="item.pickup"></p>
											</td>
											<td class="px-4 py-3">
												<p class="font-normal" x-text="item.dropoff"></p>
											</td>
											<td class="px-4 py-3">
												<p class="font-normal" x-text="item.distance"> </p>
											</td>
											<td class="px-4 py-3">
												<p class="font-normal" x-text="item.amount"> </p>
											</td>
											<td class="px-4 py-3">
												<p class="font-normal" x-text="item.payment"> </p>
											</td>
											<td class="px-4 py-3">
												<span x-text="item.timestamp"></span>
											</td>
											<td class="px-4 py-3">
												<span x-text="item.endtime"></span>
											</td>
										</tr>
									</template>
									<tr x-show="isEmpty()">
										<td colspan="9" class="text-center py-3 text-gray-900 text-sm">No matching records found.</td>
									</tr>
								</tbody>
							</table>
							<div class="grid px-4 py-3 text-xs font-semibold tracking-wide text-gray-500 uppercase border-t dark:border-gray-700 bg-gray-50 sm:grid-cols-9 dark:text-gray-400 dark:bg-gray-800">
								<span class="flex items-center col-span-3"></span>
								<span class="col-span-2"></span>
								<!-- Pagination -->
								<span class="flex col-span-4 mt-2 sm:mt-auto sm:justify-end">
									<nav aria-label="Table navigation">
										<ul class="inline-flex items-center">
											<li>
												<button class="px-3 py-1 mx-2 border rounded-md rounded-l-lg focus:outline-none focus:shadow-outline-purple" aria-label="Previous" @click="changePage(currentPage - 1)">
													NEXT
												</button>
											</li>
											
											<li>
												<button class="px-3 py-1 mx-2 border rounded-md rounded-r-lg focus:outline-none focus:shadow-outline-purple" aria-label="Next" @click="changePage(currentPage + 1)">
													PREV
												</button>
											</li>
										</ul>
									</nav>
								</span>
							</div>
						</div>
					</div>		
				</div>
			</div>
			
			
			
		</div>
    </main>
	
</div>
</div>
<?php
$data = [];
foreach($rides as $entry){
	array_push($data, array('reference' => $entry['ride_token'],
							'fullname' => $entry['user_id'],
							'pickup' => $entry['start_address'],
							'dropoff' => $entry['end_address'],
							'distance' => $entry['route_direction'],
							'amount' => $entry['amount'].' UGX',
							'payment' => $entry['payment_method'],
							'timestamp' => date('F d, Y h:i:s a', strtotime($entry['start_time'])),
							'endtime' => date('F d, Y h:i:s a', strtotime($entry['end_time']))));
}
?>
<script>
let dati = <?=json_encode($data);?>;
</script>	
<!-- partial -->
<script src='https://cdn.jsdelivr.net/npm/fuse.js/dist/fuse.js'></script>
<script  src="<?=DOMAIN?>assets/js/datatable.js"></script>