
    <!--::footer_part start::-->
    <footer class="footer_part">
        <div class="container">
            <hr>
            <div class="row">
                <div class="col-lg-8">
                    <div class="copyright_text">
                        <P><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | <a href="<?=DOMAIN?>" target="_blank">CoolBoda</a> Ugandan Company
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></P>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="footer_icon social_icon">
                        <ul class="list-unstyled">
                            <li><a href="#" class="single_social_icon"><i class="fab fa-facebook-f"></i></a></li>
                            <li><a href="#" class="single_social_icon"><i class="fab fa-twitter"></i></a></li>
                            <li><a href="#" class="single_social_icon"><i class="fab fa-instagram"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--::footer_part end::-->

    <!-- jquery plugins here-->
    <!-- jquery -->
    <script src="<?=DOMAIN ?>assets/js/jquery-1.12.1.min.js"></script>
    <!-- popper js -->
    <script src="<?=DOMAIN ?>assets/js/popper.min.js"></script>
    <!-- bootstrap js -->
    <script src="<?=DOMAIN ?>assets/js/bootstrap.min.js"></script>
    <!-- easing js -->
    <script src="<?=DOMAIN ?>assets/js/jquery.magnific-popup.js"></script>
    <!-- swiper js -->
    <script src="<?=DOMAIN ?>assets/js/swiper.min.js"></script>
    <!-- swiper js -->
    <script src="<?=DOMAIN ?>assets/js/masonry.pkgd.js"></script>
    <!-- particles js -->
    <script src="<?=DOMAIN ?>assets/js/owl.carousel.min.js"></script>
    <script src="<?=DOMAIN ?>assets/js/jquery.nice-select.min.js"></script>
    <!-- slick js -->
    <script src="<?=DOMAIN ?>assets/js/slick.min.js"></script>
    <script src="<?=DOMAIN ?>assets/js/jquery.counterup.min.js"></script>
    <script src="<?=DOMAIN ?>assets/js/waypoints.min.js"></script>
    <script src="<?=DOMAIN ?>assets/js/contact.js"></script>
    <script src="<?=DOMAIN ?>assets/js/jquery.ajaxchimp.min.js"></script>
    <script src="<?=DOMAIN ?>assets/js/jquery.form.js"></script>
    <script src="<?=DOMAIN ?>assets/js/jquery.validate.min.js"></script>
    <script src="<?=DOMAIN ?>assets/js/mail-script.js"></script>
    <!-- custom js -->
    <script src="<?=DOMAIN ?>assets/js/custom.js"></script>
</body>
</html>