<!doctype html>
<html lang="zxx">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
	<meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><?php echo TITLE ?></title>
    <link rel="icon" href="<?=DOMAIN ?>assets/img/favicon.png">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="<?=DOMAIN ?>assets/css/bootstrap.min.css">
    <!-- animate CSS -->
    <link rel="stylesheet" href="<?=DOMAIN ?>assets/css/animate.css">
    <!-- owl carousel CSS -->
    <link rel="stylesheet" href="<?=DOMAIN ?>assets/css/owl.carousel.min.css">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="<?=DOMAIN ?>assets/css/all.css">
    <!-- flaticon CSS -->
    <link rel="stylesheet" href="<?=DOMAIN ?>assets/css/flaticon.css">
    <link rel="stylesheet" href="<?=DOMAIN ?>assets/css/themify-icons.css">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="<?=DOMAIN ?>assets/css/magnific-popup.css">
    <!-- swiper CSS -->
    <link rel="stylesheet" href="<?=DOMAIN ?>assets/css/slick.css">
    <!-- style CSS -->
    <link rel="stylesheet" href="<?=DOMAIN ?>assets/css/style.css">
	
	<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
</head>
<body>