<!DOCTYPE html>
<html :class="{ 'theme-dark': dark }" x-data="data()" lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Dashboard | <?php echo TITLE ?></title>
		<link
		  href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap"
		  rel="stylesheet"
		/>
		<link rel="shortcut icon" type="image/x-icon" href="<?php echo DOMAIN ?>assets/images/favicon.ico">
		<link rel="stylesheet" href="<?=DOMAIN?>assets/css/tailwind.output.css" />
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.css"/>
		
		<!--<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>-->
		<script src='https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.3.5/dist/alpine.min.js' defer></script>
		<script src="<?=DOMAIN?>assets/js/init-alpine.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js" ></script>
	</head>
<body>